### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by eabase** [measuresforjustice/textricator#18]
Maybe something to handle?

```bash
# ./textricator.bat form --config=xxy.yml xxy.pdf xxy.csv

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.parboiled.transform.AsmUtils (file:/F:/pathto/lib/parboiled-java-1.3.1.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.parboiled.transform.AsmUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
...
```

**Comment by stephenbyrne-mfj** [comment]
https://github.com/measuresforjustice/expr/issues/7

**Comment by eabase** [comment]
@stephenbyrne-mfj 

Thanks for responding here. Unfortunately I don't have the java know-how on how to fix this. What is required to do to fix this?

**Comment by stephenbyrne-mfj** [comment]
I am hoping that parboiled will fix it (so we just have to updated to the latest version of parboiled) before Java removes the ability to make the reflection calls that this method makes: https://github.com/sirthias/parboiled/blob/master/parboiled-java/src/main/java/org/parboiled/transform/AsmUtils.java#L202

**Comment by eabase** [comment]
IDK, know if you have seen my posts there (parboiled repo) just a few minutes ago, but it looks like its owner have no longer any intention maintain it, AFAICT.  Someone suggested finding/using a different expression parser...

* https://github.com/sirthias/parboiled/issues/103
* https://github.com/measuresforjustice/expr/issues/7

**Comment by eabase** [comment]
I doubt they will as it seem that maintainer is no longer able to maintain that project..

**Comment by stephenbyrne-mfj** [comment]
When Java breaks support for it, I will either find a different peg parser or write a custom parser for expr.
