### ISSUE TITLE
What version of Yaml is the form type parsing following/using?

### ISSUE THREAD

**Issue by eabase** [measuresforjustice/textricator#22]
exactly that

Trying to understand why the "Type: integer" doesn't work.

Reading:
* https://yaml.org/spec/1.2/spec.html

**Comment by stephenbyrne-mfj** [comment]
The error was from expr, not Yaml parsing. expr version 5 (https://github.com/measuresforjustice/expr/releases/tag/v5.0.25) replaced `integer` and `double` with `number`.

Textricator uses jackson-dataformat-yaml (https://github.com/FasterXML/jackson-dataformats-text), which uses snakeyaml-engine (https://bitbucket.org/asomov/snakeyaml-engine/src/master/), which claims to support YaML 1.2.
