### ISSUE TITLE
Regex problem

### ISSUE THREAD

**Issue by ozkarah** [measuresforjustice/textricator#30]
I cannot make following condition return true for this input:
Text(content=Configuration: UK, pageNumber=1, ulx=115.8, uly=347.16, lrx=177.86113, lry=347.16, font=JIWRWC+ArialUnicodeMS, fontSize=7.92, color=default, backgroundColor=null, link=null)

onCheckCondition : configuration->text =~ /^Configuration/ and  114 < ulx < 135 and font = "JIWRWC+ArialUnicodeMS"->false

configuration: 'text =~ /^Configuration/ and  114 < ulx < 135 and font = "JIWRWC+ArialUnicodeMS"'

I guess the problem is in the syntax of regular expression but when I try same reg ex on online regex testers it matches. Do you have any suggestion on that ?

**Comment by mweber55** [comment]
@ozkarah Just add a wildcard for characters after the leading "Configuration" to your regex like so:

`configuration: 'text =~ /^Configuration.*/ and 114 < ulx < 135 and font = "JIWRWC+ArialUnicodeMS"'`
