### ISSUE TITLE
footer ignores from top, not bottom

### ISSUE THREAD

**Issue by qubodup** [measuresforjustice/textricator#32]
The comment in 

```
footer:
    # ignore anything less than this many points from the bottom, default and per-page
  default: 700
```

in
https://github.com/measuresforjustice/textricator/blob/main/src/test/resources/io/mfj/textricator/examples/school-employee-list.yml
https://github.com/measuresforjustice/textricator/blob/main/README.md
is incorrect, currently if functions like this:

    # ignore anything more than this many points from the top, default and per-page

Not sure if the comment is a bug or the way it currently works is a bug.

Noticed this while making a tutorial video found at https://youtu.be/1pGO-cKMPLA

change the footer default to "1" to see the difference.

    .\textricator.bat form --config=bottomleft.yml .\bottomleft.pdf --output-format=csv

[bottomleft.zip](https://github.com/measuresforjustice/textricator/files/7859338/bottomleft.zip) contains:
- bottomleft.pdf
- bottomleft.yml

**Comment by stephen-byrne** [comment]
It is supposed to read "more than". The point is to ignore everything at the bottom of the page: everything more than N pixels from the top.
