### ISSUE TITLE
So this is dead, right?

### ISSUE THREAD

**Issue by noyannus** [measuresforjustice/textricator#50]
:-((

**Comment by stephen-byrne** [comment]
I will see if I can get somebody at Measures for Justice to merge my PRs and make a release. If I do not hear back, I will fork it.

**Comment by wstumbo-mfj** [comment]
No, not dead.  Just my notifications got hosed somewhere along the line and I wasn't seeing new issues come in.

**Comment by noyannus** [comment]
That is good news! I'll edit the title.
