### ISSUE TITLE
Parsing and debugging itext5 in the future: possible?

### ISSUE THREAD

**Issue by noyannus** [measuresforjustice/textricator#58]
`itext7` and `pdfbox` break parsing that worked on `itext5`. That their different parsing engines deliver different results is to be expected, duh. Bus some projects require a specific extractor. E.g. I am currently working on a project that requires `itext5`, because whole text segments of some of its input PDFs are broken into words by `pdfbox` or irregular chunks by `itext7`. The latter swallows digits, too, but not all of them. 

It would be good to know whether, now that `itext5` is deprecated, it will eventually drop out of textricator? Then, some probematic PDFs will require a loop through each text segment -- or will there be a replacement with similar parsing? Maybe `itext8` that is out now -- are there plans to include it in textricator?

Related, but not worth opening a separate issue: The debug mode of the current version seems to be nailed to itext7 already. It returns `-- Using extractor "pdf.itext7" for input format "pdf.itext5".` and `-- Using extractor "pdf.itext7" for input format "pdf.pdfbox".`, resp. I guess that is a precaution to stay consistent when debugging textricator, but as a side effect it disables debugging YAMLs that have to run `itext5` or `pdfbox`.

Is it possible to enable debugging for `pdfbox` and `itext5`? ...It's such a d'n useful tool.

---

Examples (digits replaced with "0", characters with "a")

itext5, desired result
```
00.00.00
00.00.00
aaaaaaaaaaaaaaa
0,00
-
00.00.00
00.00.00
aa aaaa a-aa 0aaa0a, aaaaaaaa
00,00
-
00.00.00
00.00.00
aaaaaaaaaa
000,00
+
```

itext7
```
0
0
0
0
0
0
aaaa
a
a
aaa
aa
a
aa
a
 
0,
0
-
0
0
0
0
0
0
aa 
aaaa 
a-
aa 
0aaa0a,
 
a
aaaaaaa
00,
0
-
0
0
0
0
0
0
aa
aa
aaa
aaa
 
000,
0
+
```

pdfbox
```
00.00.00
00.00.00
aaaaaaaaaaaaaaa
0,00
-
00.00.00
00.00.00
aa
aaaa
a-aa
0aaa0a,
aaaaaaaa
00,00
-
00.00.00
00.00.00
aaaaaaaaaa
000,00
+
```

**Comment by wstumbo-mfj** [comment]
There is no specific date to remove the existing itext5 code from Textricator.  However, since it is no longer being actively developed and maintenance is security updates only, I want to start the process of moving away from it.  I imagine there will be a day that all support drops and I want to be positioned to end our support at that point in time, if not before.

Your post brings up one of the reasons for creating issue #57  - what's going to break and what are the implications of that?  What workarounds exist and what information do we need to put in place to help users migrate?

**Comment by noyannus** [comment]
The only change I've seen so far is, text segments that were treated as a single entity by `itext5` are broken into several chunks, single characters (but not always) or words by the two other PDF extractors.

`pdfbox` breaks the chunks apparently at spaces (and other whitespace?) that are clipped. The width of that space depends on font and varies. 

If the gap between text segments is *always* larger than the largest space, the segments can be concatenated with a loop over all chunks (not tested), but I guess you thought already of that.

To set a mininum gap width, you could introduce a global value; sort of a horizontal and reverse (separate instead of treat as same) `maxRowDistance`. A `minSegmentGap` or so. Where `maxRowDistance` tolerates, `minFieldDistance` discriminates.

But that introduces an error source, when gaps are too narrow.

---

itext is open source so maybe you could fork and copy relevant settings parts from itext5 to itextX. If only parameters are different, that should be easy (erm... never believe that!). If the code has changed transferring code from itex5 could be quite a challenge.

Also, there should be other extractors, i.e. python scripts (python has mature libraries for that, I believe), you could with textractor.

**Comment by stephen-byrne** [comment]
I put the debug logs in the itext5 extractor because it is more complicated than either the itext7 or the pdfbox extractors, and it was often helpful figuring out what was going on. With the itext7 and pdfbox extractors, it is a much simpler conversion from what the itext7/pdfbox library exposes and what textricator outputs, so more debugging was never useful.

**Comment by stephen-byrne** [comment]
Somebody could write a python-based extractor that generates the same JSON format or the same CSV format that Textricator generates, and then you could use `textricator form --input-format=csv/json` on that output.

**Comment by stephen-byrne** [comment]
> It returns -- Using extractor "pdf.itext7" for input format "pdf.itext5".

I cannot reproduce this. How did you get it to happen?

**Comment by noyannus** [comment]
>>    It returns -- Using extractor "pdf.itext7" for input format "pdf.itext5".

> I cannot reproduce this. How did you get it to happen?

I can't reproduce now either. I'm sure it was real, I remember copy-pasting the line.   ~8-/


> Somebody could write a python-based extractor that generates the same JSON format or the same CSV format that Textricator generates, and then you could use textricator form --input-format=csv/json on that output.

I guess it would be easier to adapt some existing python script/library from the web to extract everything with its coordinates and add the conditions for filtering and the code for output ordering. Going full python would make a state machine structure an unneccessary wrapper, though, and it would no longer be recognizable as textricator.


As my initial question has been anwerede, I'll close this as resolved. Thank you for your time to explain!
