### ISSUE TITLE
Create a simple GUI

### ISSUE THREAD

**Issue by stephenbmfj** [measuresforjustice/textricator#6]
Don't try to help build the .yaml file, just emulate the behavior of the web ui.

**Comment by o-data** [comment]
Hi guys, this author mentioned that there is a GUI via browser version. Where is that? I can't find any mention or links to the GUI version.

**Comment by eabase** [comment]
bump?

**Comment by stephenbyrne-mfj** [comment]
I wrote the GUI in JavaFX, which I have since stopped using, for various reasons. I plan to rewrite the GUI in Swing.
