### ISSUE TITLE
compile issues due to dependencies

### ISSUE THREAD

**Issue by d-rep** [measuresforjustice/textricator#9]
Building with maven using `mvn clean install` always fails due to certain artifacts referenced in the [pom.xml](https://github.com/measuresforjustice/textricator/blob/master/pom.xml) that don't actually exist in [Maven Central](https://search.maven.org/):

- `org.jetbrains.dokka:dokka-maven-plugin:0.9.18`
- `io.mfj:expr:4.1.17`   (4.1.16 is latest)

In addition, I had to upgrade from `<kotlin.version>1.3.50</kotlin.version>` to `<kotlin.version>1.3.71</kotlin.version>` or I got an error about a missing class.

Also, downstream projects like [textricator-web](https://github.com/measuresforjustice/textricator-web) and [textricator-gui](https://github.com/measuresforjustice/textricator-gui) reference `<version.textricator>9.2.58</version.textricator>` which hasn't been released.  This project's [pom.xml](https://github.com/measuresforjustice/textricator/blob/master/pom.xml) should have its artifact version updated from `9.2-SNAPSHOT` and republished to Maven Central.

**Comment by stephenbyrne-mfj** [comment]
The latest version uses Kotlin 1.4.10,and the latest `io.mfj:expr`, which has been released to maven central.

`dokka-maven-plugin` is published to jcenter. https://github.com/Kotlin/dokka/issues/41

Ultimately I think the solution is going to be switching from Maven to Gradle.
